INGESTION : 
    URL : 'https://api.coingecko.com/api/v3/coins/markets'
    PARAMS : { 'vs_currency': 'usd','order': 'market_cap_desc','per_page': '100','page': '1','sparkline': 'false'}
    SYMBOLS : ["BTC", "ETH", "LTC", "XRP", "BCH", "ADA", "SOL", "DOT", "DOGE", "MATIC", "AVAX", "LINK", "XLM", "TRX", "VET", "ALGO", "FIL", "SHIB",  "CRO", "MKR", "AAVE", "UNI", "SAND"]